mode: debug
cors:
  allow_credentials: false
  allow_headers:
    - '*'
  allow_methods:
    - GET
    - POST
    - OPTIONS
    - PUT
    - DELETE
  allow_origins:
    - '*'
  enable: false
  max_age: 7200

database:
  driver: mysql
  mysql:
    charset: utf8
    host: 127.0.0.1:3306
    name: atlas
    user: root
    password: 123456
    pool:
      max: 20
      min: 5
    ssl: false

  sqlite:
    dsn: data/zeus.db